apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
     github.com/project-slug: ForrestIsARealGoodman/ladder
  #  backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: forrestisagoodman@gmail.com
  lifecycle: experimental
